version: 2
updates:
  # Github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
  #Â Root Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # Functional tests Go module
  - package-ecosystem: "gomod"
    directory: "/deploy"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"
